import React, { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronRight, File, FileImage, FileText, FolderOpen, Forward, Play, Trash2, Video, X } from "lucide-react";
import type { CloudAsset } from "../api/cloudApi";
import { cloudApi } from "../api/cloudApi";
import { usePreviewUrl } from "../../../hooks/usePreviewUrl";
import { PersonalCloudAvatar } from "./PersonalCloudAvatar";

const formatBytes = (value: string | number) => {
  const bytes = Number(value);
  if (!Number.isFinite(bytes) || bytes < 0) return "—";
  const units = ["B", "KB", "MB", "GB", "TB"];
  let index = 0;
  let sized = bytes;
  while (sized >= 1024 && index < units.length - 1) { sized /= 1024; index += 1; }
  return `${sized >= 10 || index === 0 ? Math.round(sized) : sized.toFixed(1)} ${units[index]}`;
};
const formatWhen = (value: string) => {
  const date = new Date(value);
  const hours = Math.floor((Date.now() - date.getTime()) / 3_600_000);
  return Number.isNaN(hours) ? "" : hours < 1 ? "Vừa xong" : hours < 24 ? `${hours} giờ trước` : date.toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit" });
};
const fileIcon = (asset: CloudAsset) => asset.mediaType === "image" ? <FileImage className="h-5 w-5 text-sky-600" /> : asset.mediaType === "video" ? <Video className="h-5 w-5 text-violet-600" /> : asset.mimeType.includes("pdf") ? <FileText className="h-5 w-5 text-red-600" /> : <File className="h-5 w-5 text-text-muted" />;

export const StorageUsageBar: React.FC<{ usedBytes: string; limitBytes: string }> = ({ usedBytes, limitBytes }) => {
  const used = Number(usedBytes); const limit = Number(limitBytes); const percent = limit > 0 ? Math.max(0, Math.min(100, used / limit * 100)) : 0;
  const visualPercent = percent > 0 ? Math.max(2.5, percent) : 0;
  const color = percent >= 95 ? "bg-danger" : percent >= 80 ? "bg-warning" : "bg-brand-solid";
  return <><div className="mt-3 h-2 overflow-hidden rounded-full bg-surface-hover" role="progressbar" aria-label="Dung lượng đã sử dụng" aria-valuemin={0} aria-valuemax={limit || 0} aria-valuenow={Math.min(used, limit || used)} aria-valuetext={`${formatBytes(used)} trên ${formatBytes(limit)} đã dùng`}><div className={`h-full rounded-full ${color}`} style={{ width: `${visualPercent}%` }} /></div><div className="mt-2 flex justify-between gap-2 text-xs text-text-muted"><span>Còn lại {formatBytes(Math.max(0, limit - used))}</span><span>{percent > 0 && percent < 0.1 ? "<0,1%" : `${percent.toFixed(percent < 10 ? 1 : 0)}%`}</span></div></>;
};
export const CloudStorageCard: React.FC<{ quota: { limitBytes: string; usedBytes: string; reservedBytes: string } | null; onManage: () => void }> = ({ quota, onManage }) => {
  if (!quota) return <div className="rounded-xl border border-border/70 p-4 text-sm text-text-muted">Đang tải dung lượng lưu trữ…</div>;
  const used = String(Number(quota.usedBytes) + Number(quota.reservedBytes));
  return <section className="rounded-xl border border-border/70 bg-surface p-4 shadow-sm"><h3 className="text-sm font-semibold">Dung lượng lưu trữ</h3><p className="mt-1 text-sm">{formatBytes(used)} <span className="text-text-muted">/ {formatBytes(quota.limitBytes)}</span></p><StorageUsageBar usedBytes={used} limitBytes={quota.limitBytes} /><button type="button" onClick={onManage} className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-brand-solid hover:underline"><FolderOpen className="h-4 w-4" />Xem và quản lý Hacom Cloud</button></section>;
};
export const SidebarSection: React.FC<{ title: string; count?: number; children: React.ReactNode }> = ({ title, count, children }) => {
  const key = `hacom-cloud-sidebar:${title}`; const [open, setOpen] = useState(() => sessionStorage.getItem(key) !== "closed");
  const toggle = () => setOpen((current) => { sessionStorage.setItem(key, current ? "closed" : "open"); return !current; });
  return <section className="border-t border-border/70 pt-4"><button type="button" className="flex w-full items-center justify-between text-left" onClick={toggle} aria-expanded={open}><span className="text-sm font-semibold">{title}{typeof count === "number" && <span className="ml-1 text-text-muted">({count})</span>}</span>{open ? <ChevronDown className="h-4 w-4 text-text-muted" /> : <ChevronRight className="h-4 w-4 text-text-muted" />}</button>{open && <div className="mt-3">{children}</div>}</section>;
};
export const CloudEmptyState: React.FC<{ text: string }> = ({ text }) => <p className="rounded-lg bg-surface-hover px-3 py-4 text-center text-sm text-text-muted">{text}</p>;
export const CloudSidebarSkeleton: React.FC = () => <div className="space-y-4 p-4" aria-label="Đang tải thông tin Hacom Cloud"><div className="mx-auto h-16 w-16 animate-pulse rounded-full bg-surface-hover" />{[1, 2, 3].map((item) => <div key={item} className="h-20 animate-pulse rounded-xl bg-surface-hover" />)}</div>;
const CloudMediaTile: React.FC<{ asset: CloudAsset; conversationId: string; onOpen: (asset: CloudAsset) => void }> = ({ asset, conversationId, onOpen }) => { const { url } = usePreviewUrl(conversationId, asset.attachmentId ?? "", { autoFetch: Boolean(asset.attachmentId) }); return <button type="button" onClick={() => onOpen(asset)} className="relative aspect-square overflow-hidden rounded-lg bg-surface-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-solid" aria-label={`Mở ${asset.originalFilename}`}>{url && asset.mediaType === "image" ? <img src={url} alt="" className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center">{asset.mediaType === "video" ? <Video className="h-6 w-6 text-text-muted" /> : <FileImage className="h-6 w-6 text-text-muted" />}</span>}{asset.mediaType === "video" && <span className="absolute inset-0 flex items-center justify-center bg-black/20"><Play className="h-6 w-6 fill-white text-white" /></span>}</button>; };
export const RecentMediaGrid: React.FC<{ assets: CloudAsset[]; conversationId: string; onOpen: (asset: CloudAsset) => void }> = ({ assets, conversationId, onOpen }) => !assets.length ? <CloudEmptyState text="Chưa có ảnh hoặc video gần đây" /> : <div className="grid grid-cols-3 gap-2">{assets.slice(0, 6).map((asset) => <CloudMediaTile key={asset.id} asset={asset} conversationId={conversationId} onOpen={onOpen} />)}</div>;
export const CloudFileRow: React.FC<{ asset: CloudAsset; onPreview: (asset: CloudAsset) => void; onForward?: (asset: CloudAsset) => void; onTrash: (asset: CloudAsset) => void }> = ({ asset, onPreview, onForward, onTrash }) => <li className="flex min-w-0 items-center gap-3 rounded-lg px-1 py-2 hover:bg-surface-hover"><button type="button" onClick={() => onPreview(asset)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="shrink-0">{fileIcon(asset)}</span><span className="min-w-0"><span title={asset.originalFilename} className="block truncate text-sm">{asset.originalFilename}</span><span className="block text-xs text-text-muted">{formatBytes(asset.sizeBytes)} · {formatWhen(asset.createdAt)}</span></span></button><span className="flex shrink-0">{asset.messageId && onForward && <button type="button" aria-label={`Chuyển tiếp ${asset.originalFilename}`} onClick={() => onForward(asset)} className="rounded p-1.5 text-text-muted hover:bg-surface hover:text-text-primary"><Forward className="h-4 w-4" /></button>}<button type="button" aria-label={`Chuyển ${asset.originalFilename} vào thùng rác`} onClick={() => onTrash(asset)} className="rounded p-1.5 text-text-muted hover:bg-surface hover:text-danger"><Trash2 className="h-4 w-4" /></button></span></li>;
export const RecentFileList: React.FC<{ assets: CloudAsset[]; onPreview: (asset: CloudAsset) => void; onForward?: (asset: CloudAsset) => void; onTrash: (asset: CloudAsset) => void; onManage: () => void }> = ({ assets, onPreview, onForward, onTrash, onManage }) => !assets.length ? <CloudEmptyState text="Chưa có tệp nào trong Hacom Cloud" /> : <><ul className="divide-y divide-border/50">{assets.slice(0, 5).map((asset) => <CloudFileRow key={asset.id} asset={asset} onPreview={onPreview} onForward={onForward} onTrash={onTrash} />)}</ul><button type="button" className="mt-3 text-sm font-medium text-brand-solid hover:underline" onClick={onManage}>Xem tất cả tệp</button></>;
export const CloudIdentity: React.FC = () => <div className="px-4 pb-5 pt-6 text-center"><PersonalCloudAvatar size="lg" className="mx-auto" /><h2 className="mt-3 text-base font-semibold">Cloud của tôi</h2><p className="mx-auto mt-1 max-w-[18rem] text-sm leading-5 text-text-muted">Lưu trữ và truy cập nhanh các nội dung quan trọng của bạn</p></div>;
const CloudManagerDialog: React.FC<{ assets: CloudAsset[]; onClose: () => void; onPreview: (asset: CloudAsset) => void; onForward?: (asset: CloudAsset) => void; onTrash: (asset: CloudAsset) => void }> = ({ assets, onClose, onPreview, onForward, onTrash }) => { const [query, setQuery] = useState(""); useEffect(() => { const key = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [onClose]); const filtered = assets.filter((asset) => asset.originalFilename.toLowerCase().includes(query.toLowerCase())); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-label="Quản lý Hacom Cloud"><div className="flex max-h-[80vh] w-full max-w-xl flex-col rounded-xl bg-surface shadow-xl"><header className="flex items-center justify-between border-b border-border/70 p-4"><h2 className="font-semibold">Quản lý Hacom Cloud</h2><button type="button" onClick={onClose} className="rounded p-1 hover:bg-surface-hover" aria-label="Đóng"><X className="h-5 w-5" /></button></header><div className="p-4"><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tệp" className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm outline-none focus:border-brand-solid" /></div><ul className="min-h-0 overflow-y-auto px-4 pb-4">{filtered.length ? filtered.map((asset) => <CloudFileRow key={asset.id} asset={asset} onPreview={onPreview} onForward={onForward} onTrash={onTrash} />) : <CloudEmptyState text="Không tìm thấy tệp phù hợp" />}</ul></div></div>; };
export const HacomCloudInfoSidebar: React.FC<{ open: boolean; onClose: () => void; quota: { limitBytes: string; usedBytes: string; reservedBytes: string } | null; assets: CloudAsset[]; conversationId: string; loading?: boolean; onChanged: () => Promise<void> | void; onPreview: (asset: CloudAsset) => void; onForward?: (asset: CloudAsset) => void }> = ({ open, onClose, quota, assets, conversationId, loading = false, onChanged, onPreview, onForward }) => { const [managerOpen, setManagerOpen] = useState(false); const available = useMemo(() => assets.filter((asset) => asset.status === "available"), [assets]); const media = useMemo(() => available.filter((asset) => asset.mediaType === "image" || asset.mediaType === "video").slice(0, 6), [available]); const trash = async (asset: CloudAsset) => { await cloudApi.trash(asset.id); await onChanged(); }; return <><aside className={`${open ? "translate-x-0 lg:w-[var(--app-inspector-width)] lg:border-l" : "translate-x-full lg:w-0 lg:border-l-0"} fixed inset-y-0 right-0 z-40 flex w-[min(100vw,400px)] overflow-hidden border-l border-border/70 bg-surface shadow-xl transition-transform duration-200 lg:static lg:z-auto lg:shrink-0 lg:shadow-none lg:transition-[width]`} aria-hidden={!open}><div className="flex h-full w-full flex-col lg:w-[var(--app-inspector-width)]"><header className="flex min-h-[var(--app-header-height)] shrink-0 items-center justify-between border-b border-border/70 px-4"><strong>Thông tin Hacom Cloud</strong><button type="button" className="rounded p-1 hover:bg-surface-hover" onClick={onClose} aria-label="Đóng thông tin Hacom Cloud"><X className="h-5 w-5" /></button></header>{loading ? <CloudSidebarSkeleton /> : <div className="min-h-0 flex-1 overflow-y-auto"><CloudIdentity /><div className="space-y-4 px-4 pb-6"><CloudStorageCard quota={quota} onManage={() => setManagerOpen(true)} /><SidebarSection title="Ảnh và video gần đây" count={media.length}><RecentMediaGrid assets={media} conversationId={conversationId} onOpen={onPreview} /></SidebarSection><SidebarSection title="Tệp gần đây" count={available.length}><RecentFileList assets={available} onPreview={onPreview} onForward={onForward} onTrash={trash} onManage={() => setManagerOpen(true)} /></SidebarSection></div></div>}</div></aside>{managerOpen && <CloudManagerDialog assets={available} onClose={() => setManagerOpen(false)} onPreview={onPreview} onForward={onForward} onTrash={trash} />}</>; };
