/**
 * Centralized route paths to keep navigation and route config consistent.
 */
export const ROUTE_PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  ACTIVATION: "/activation",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  FORCE_CHANGE_PASSWORD: "/force-change-password",
  PENDING_HR_LINK: "/pending-hr-link",
  CHAT: "/chat",
  CHAT_DETAIL: "/chat/:conversationId?",
  FRIENDS: "/friends",
  FRIEND_DISCOVERY: "/friend-discovery/:shareCode",
  JOIN_BY_TOKEN: "/join/:token",
  CALENDAR_JOIN_BY_SHARE_LINK: "/calendar/join/:token",
  SETTINGS: "/settings",
  MAINTENANCE: "/maintenance",
  TASKS: "/tasks",
  TIMESHEET: "/timesheet",
  TEAM_TIMESHEET: "/timesheet/team",
  LEAVE: "/leave",
  CALENDAR: "/calendar",
  AI_ASSISTANT: "/ai-assistant",
  WORK_REPORT_DRAFTS: "/work-report-drafts",
  // My Documents is a first-class chat conversation, not a separate module.
  CLOUD: "/chat/my-documents",
  CLOUD_MANAGE: "/cloud/manage",
  CLOUD_LEGACY: "/cloud",
  ARCHIVE: "/archive",
  NOTIFICATIONS: "/notifications",
  HELP: "/help",
  FAQ: "/faq",
  TIPS: "/tips",
  REPORT_ISSUE: "/report-issue",
  PRIVACY_POLICY: "/privacy-policy",
  DATA_DELETION: "/data-deletion",
  SUPPORT: "/support",
  TERMS: "/terms",
} as const;
