export const queryKeys = {
  currentAdmin: ['current-admin'] as const,
  accessStatus: ['access-status'] as const,
  accessIpRequests: (params: string) => ['access-ip-requests', params] as const,
  accessIpRequestDetail: (id: string) => ['access-ip-request-detail', id] as const,
  accessIpRequestHistory: (id: string) => ['access-ip-request-history', id] as const,
  usersList: (params: string) => ['users-list', params] as const,
  userDetail: (id: string) => ['user-detail', id] as const,
  userSessions: (id: string, params: string) => ['user-sessions', id, params] as const,
  userDevices: (id: string, params: string) => ['user-devices', id, params] as const,
  hrEmployeesList: (params: string) => ['hr-employees-list', params] as const,
  hrEmployeesRoot: ['hr-employees-list'] as const,
  hrEmployeeDetail: (id: string) => ['hr-employee-detail', id] as const,
  hrEmployeeImportValidation: (stamp: string) => ['hr-import-validation', stamp] as const,
  hrEmployeeImportBatch: (batchId: string) => ['hr-import-batch', batchId] as const,
  hrEmployeeImportReport: (batchId: string) => ['hr-import-report', batchId] as const,
  auditLogs: (params: string) => ['audit-logs', params] as const,
  smtpSettings: ['smtp-settings'] as const,
  emailTemplates: ['email-templates'] as const,
  emailTemplateDetail: (code: string) => ['email-template-detail', code] as const,
  serviceHealth: ['service-health'] as const,
  monitoringOverview: (range: string) => ['monitoring-overview', range] as const,
  dashboardSummary: (stamp: string) => ['dashboard-summary', stamp] as const,
};
