type QueryParams = object | string | number | boolean | null | undefined;

export const queryKeys = {
  currentAdmin: ['current-admin'] as const,
  accessStatus: ['access-status'] as const,
  authorityUsersRoot: ['authority-users'] as const,
  authorityUsers: (params: QueryParams) => ['authority-users', params] as const,
  authorityUserDetailRoot: ['authority-user-detail'] as const,
  authorityUserDetail: (userId: string) => ['authority-user-detail', userId] as const,
  accessIpRequestsRoot: ['access-ip-requests'] as const,
  accessIpRequests: (params: QueryParams) => ['access-ip-requests', params] as const,
  accessIpRequestDetailRoot: ['access-ip-request-detail'] as const,
  accessIpRequestDetail: (id: string) => ['access-ip-request-detail', id] as const,
  accessIpRequestHistoryRoot: ['access-ip-request-history'] as const,
  accessIpRequestHistory: (id: string) => ['access-ip-request-history', id] as const,
  usersRoot: ['users-list'] as const,
  usersList: (params: QueryParams) => ['users-list', params] as const,
  userDetailRoot: ['user-detail'] as const,
  userDetail: (id: string) => ['user-detail', id] as const,
  userSessionsRoot: ['user-sessions'] as const,
  userSessions: (id: string, params: QueryParams) => ['user-sessions', id, params] as const,
  userDevicesRoot: ['user-devices'] as const,
  userDevices: (id: string, params: QueryParams) => ['user-devices', id, params] as const,
  hrEmployeesRoot: ['hr-employees-list'] as const,
  hrEmployeesList: (params: QueryParams) => ['hr-employees-list', params] as const,
  hrEmployeeDetailRoot: ['hr-employee-detail'] as const,
  hrEmployeeDetail: (id: string) => ['hr-employee-detail', id] as const,
  hrEmployeeImportValidation: (stamp: string) => ['hr-import-validation', stamp] as const,
  hrEmployeeImportBatch: (batchId: string) => ['hr-import-batch', batchId] as const,
  hrEmployeeImportReport: (batchId: string) => ['hr-import-report', batchId] as const,
  auditLogsRoot: ['audit-logs'] as const,
  auditLogs: (params: QueryParams) => ['audit-logs', params] as const,
  conversationsRoot: ['conversations'] as const,
  conversationsList: (params: QueryParams) => ['conversations', 'list', params] as const,
  conversationDetailRoot: ['conversations', 'detail'] as const,
  conversationDetail: (id: string) => ['conversations', 'detail', id] as const,
  conversationMessagesRoot: ['conversation-messages'] as const,
  conversationMessages: (conversationId: string, params: QueryParams) =>
    ['conversation-messages', conversationId, params] as const,
  smtpSettings: ['smtp-settings'] as const,
  emailTemplates: ['email-templates'] as const,
  emailTemplateDetail: (code: string) => ['email-template-detail', code] as const,
  serviceHealth: ['service-health'] as const,
  monitoringOverview: (range: string) => ['monitoring-overview', range] as const,
  dashboardSummary: (stamp: string) => ['dashboard-summary', stamp] as const,
};
